"""0001_initial_schema

Revision ID: af402504bc39
Revises: 
Create Date: 2026-09-27 21:54:51.126381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af402504bc39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('lab_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('before_state_json', sa.JSON(), nullable=True),
    sa.Column('after_state_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_lab_id'), 'audit_logs', ['lab_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('laboratories',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_identifier', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratories_code'), 'laboratories', ['code'], unique=True)
    op.create_index(op.f('ix_laboratories_id'), 'laboratories', ['id'], unique=False)
    op.create_index(op.f('ix_laboratories_is_active'), 'laboratories', ['is_active'], unique=False)
    op.create_table('test_categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_test_categories_id'), 'test_categories', ['id'], unique=False)
    op.create_table('test_packages',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_test_packages_id'), 'test_packages', ['id'], unique=False)
    op.create_table('laboratory_settings',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('report_header_html', sa.Text(), nullable=True),
    sa.Column('report_footer_html', sa.Text(), nullable=True),
    sa.Column('report_disclaimer', sa.Text(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('currency_symbol', sa.String(length=5), nullable=True),
    sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('enable_qr_verification', sa.Boolean(), nullable=True),
    sa.Column('primary_color_hex', sa.String(length=7), nullable=True),
    sa.Column('secondary_color_hex', sa.String(length=7), nullable=True),
    sa.Column('default_signatory_name', sa.String(length=150), nullable=True),
    sa.Column('default_signatory_designation', sa.String(length=150), nullable=True),
    sa.Column('default_signatory_degrees', sa.String(length=150), nullable=True),
    sa.Column('default_signatory_reg_no', sa.String(length=100), nullable=True),
    sa.Column('default_signatory_signature_url', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id')
    )
    op.create_index(op.f('ix_laboratory_settings_id'), 'laboratory_settings', ['id'], unique=False)
    op.create_table('tests',
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('test_type', sa.Enum('PATHOLOGY', 'BIOCHEMISTRY', 'RADIOLOGY', 'CARDIOLOGY', 'OTHER', name='testtypeenum'), nullable=False),
    sa.Column('sample_type', sa.Enum('WHOLE_BLOOD_EDTA', 'SERUM', 'PLASMA_CITRATE', 'URINE_ROUTINE', 'URINE_24HR', 'STOOL', 'CSF', 'SWAB', 'IMAGING', 'OTHER', name='sampletypeenum'), nullable=False),
    sa.Column('sample_container', sa.String(length=100), nullable=True),
    sa.Column('preparation_instructions', sa.Text(), nullable=True),
    sa.Column('turnaround_hours', sa.Integer(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['test_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_category_id'), 'tests', ['category_id'], unique=False)
    op.create_index(op.f('ix_tests_code'), 'tests', ['code'], unique=True)
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_index(op.f('ix_tests_is_active'), 'tests', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('lab_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'LAB_ADMIN', 'LAB_ASSISTANT', 'PATHOLOGIST', 'RADIOLOGIST', 'RECEPTIONIST', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('medical_license_number', sa.String(length=100), nullable=True),
    sa.Column('qualifications', sa.String(length=255), nullable=True),
    sa.Column('signature_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_lab_id'), 'users', ['lab_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('lab_test_prices',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'test_id', name='uq_lab_test_price')
    )
    op.create_index(op.f('ix_lab_test_prices_id'), 'lab_test_prices', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id_display', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('referring_doctor', sa.String(length=200), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'patient_id_display', name='uq_patient_lab_display')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_lab_id'), 'patients', ['lab_id'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_table('test_package_items',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['test_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'test_id', name='uq_package_test_item')
    )
    op.create_index(op.f('ix_test_package_items_id'), 'test_package_items', ['id'], unique=False)
    op.create_table('test_parameters',
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('result_type', sa.Enum('NUMBER', 'TEXT', 'SELECT', 'POSITIVE_NEGATIVE', 'RANGE', 'CUSTOM', name='resultvaluetypeenum'), nullable=False),
    sa.Column('decimal_precision', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'code', name='uq_test_param_code')
    )
    op.create_index(op.f('ix_test_parameters_id'), 'test_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_test_parameters_test_id'), 'test_parameters', ['test_id'], unique=False)
    op.create_table('bookings',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id_display', sa.String(length=32), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.String(length=10), nullable=True),
    sa.Column('referring_doctor', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SAMPLE_COLLECTED', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'booking_id_display', name='uq_booking_lab_display')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_lab_id'), 'bookings', ['lab_id'], unique=False)
    op.create_index(op.f('ix_bookings_patient_id'), 'bookings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('test_reference_ranges',
    sa.Column('parameter_id', sa.String(length=36), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age_min_years', sa.Integer(), nullable=True),
    sa.Column('age_max_years', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('critical_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('critical_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('text_normal_value', sa.String(length=255), nullable=True),
    sa.Column('display_range_string', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['test_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reference_ranges_id'), 'test_reference_ranges', ['id'], unique=False)
    op.create_index(op.f('ix_test_reference_ranges_parameter_id'), 'test_reference_ranges', ['parameter_id'], unique=False)
    op.create_table('booking_items',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=True),
    sa.Column('package_id', sa.String(length=36), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['test_packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_items_id'), 'booking_items', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id_display', sa.String(length=32), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'invoice_id_display', name='uq_invoice_lab_display')
    )
    op.create_index(op.f('ix_invoices_booking_id'), 'invoices', ['booking_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_lab_id'), 'invoices', ['lab_id'], unique=False)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_table('samples',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id_display', sa.String(length=32), nullable=False),
    sa.Column('sample_type', sa.String(length=50), nullable=False),
    sa.Column('sample_container', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'COLLECTED', 'RECEIVED', 'PROCESSING', 'REJECTED', 'COMPLETED', name='samplestatus'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_by', sa.String(length=36), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('barcode_value', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'sample_id_display', name='uq_sample_lab_display')
    )
    op.create_index(op.f('ix_samples_booking_id'), 'samples', ['booking_id'], unique=False)
    op.create_index(op.f('ix_samples_id'), 'samples', ['id'], unique=False)
    op.create_index(op.f('ix_samples_lab_id'), 'samples', ['lab_id'], unique=False)
    op.create_index(op.f('ix_samples_patient_id'), 'samples', ['patient_id'], unique=False)
    op.create_index(op.f('ix_samples_status'), 'samples', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'ONLINE', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('receipt_id_display', sa.String(length=32), nullable=False),
    sa.Column('received_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_lab_id'), 'payments', ['lab_id'], unique=False)
    op.create_table('reports',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('report_id_display', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'FINAL', 'CANCELLED', name='reportstatus'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('pdf_file_url', sa.Text(), nullable=True),
    sa.Column('hmac_digest', sa.String(length=128), nullable=True),
    sa.Column('clinical_history', sa.Text(), nullable=True),
    sa.Column('imaging_findings', sa.Text(), nullable=True),
    sa.Column('imaging_impression', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'report_id_display', name='uq_report_lab_display')
    )
    op.create_index(op.f('ix_reports_booking_id'), 'reports', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_lab_id'), 'reports', ['lab_id'], unique=False)
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_test_id'), 'reports', ['test_id'], unique=False)
    op.create_index(op.f('ix_reports_verification_token'), 'reports', ['verification_token'], unique=True)
    op.create_table('sample_tracking_events',
    sa.Column('sample_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('performer_name', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_tracking_events_id'), 'sample_tracking_events', ['id'], unique=False)
    op.create_index(op.f('ix_sample_tracking_events_sample_id'), 'sample_tracking_events', ['sample_id'], unique=False)
    op.create_table('report_attachments',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_attachments_id'), 'report_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_report_attachments_report_id'), 'report_attachments', ['report_id'], unique=False)
    op.create_table('report_versions',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_payload_json', sa.JSON(), nullable=False),
    sa.Column('amendment_reason', sa.Text(), nullable=False),
    sa.Column('amended_by', sa.String(length=36), nullable=True),
    sa.Column('amended_by_name', sa.String(length=150), nullable=True),
    sa.Column('pdf_snapshot_url', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['amended_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version_number', name='uq_report_version')
    )
    op.create_index(op.f('ix_report_versions_id'), 'report_versions', ['id'], unique=False)
    op.create_index(op.f('ix_report_versions_report_id'), 'report_versions', ['report_id'], unique=False)
    op.create_table('test_result_values',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_name', sa.String(length=200), nullable=False),
    sa.Column('parameter_code', sa.String(length=50), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range_display', sa.String(length=100), nullable=True),
    sa.Column('flag', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL_LOW', 'CRITICAL_HIGH', 'ABNORMAL', name='resultflagenum'), nullable=False),
    sa.Column('technician_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['test_parameters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'parameter_id', name='uq_report_param_val')
    )
    op.create_index(op.f('ix_test_result_values_id'), 'test_result_values', ['id'], unique=False)
    op.create_index(op.f('ix_test_result_values_parameter_id'), 'test_result_values', ['parameter_id'], unique=False)
    op.create_index(op.f('ix_test_result_values_report_id'), 'test_result_values', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_result_values_report_id'), table_name='test_result_values')
    op.drop_index(op.f('ix_test_result_values_parameter_id'), table_name='test_result_values')
    op.drop_index(op.f('ix_test_result_values_id'), table_name='test_result_values')
    op.drop_table('test_result_values')
    op.drop_index(op.f('ix_report_versions_report_id'), table_name='report_versions')
    op.drop_index(op.f('ix_report_versions_id'), table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index(op.f('ix_report_attachments_report_id'), table_name='report_attachments')
    op.drop_index(op.f('ix_report_attachments_id'), table_name='report_attachments')
    op.drop_table('report_attachments')
    op.drop_index(op.f('ix_sample_tracking_events_sample_id'), table_name='sample_tracking_events')
    op.drop_index(op.f('ix_sample_tracking_events_id'), table_name='sample_tracking_events')
    op.drop_table('sample_tracking_events')
    op.drop_index(op.f('ix_reports_verification_token'), table_name='reports')
    op.drop_index(op.f('ix_reports_test_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_lab_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_booking_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_payments_lab_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_samples_status'), table_name='samples')
    op.drop_index(op.f('ix_samples_patient_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_lab_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_booking_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_lab_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_booking_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_booking_items_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_test_reference_ranges_parameter_id'), table_name='test_reference_ranges')
    op.drop_index(op.f('ix_test_reference_ranges_id'), table_name='test_reference_ranges')
    op.drop_table('test_reference_ranges')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_patient_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_lab_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_test_parameters_test_id'), table_name='test_parameters')
    op.drop_index(op.f('ix_test_parameters_id'), table_name='test_parameters')
    op.drop_table('test_parameters')
    op.drop_index(op.f('ix_test_package_items_id'), table_name='test_package_items')
    op.drop_table('test_package_items')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_lab_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_lab_test_prices_id'), table_name='lab_test_prices')
    op.drop_table('lab_test_prices')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_lab_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tests_is_active'), table_name='tests')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_code'), table_name='tests')
    op.drop_index(op.f('ix_tests_category_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_laboratory_settings_id'), table_name='laboratory_settings')
    op.drop_table('laboratory_settings')
    op.drop_index(op.f('ix_test_packages_id'), table_name='test_packages')
    op.drop_table('test_packages')
    op.drop_index(op.f('ix_test_categories_id'), table_name='test_categories')
    op.drop_table('test_categories')
    op.drop_index(op.f('ix_laboratories_is_active'), table_name='laboratories')
    op.drop_index(op.f('ix_laboratories_id'), table_name='laboratories')
    op.drop_index(op.f('ix_laboratories_code'), table_name='laboratories')
    op.drop_table('laboratories')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_lab_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
